### ISSUE TITLE
Will you release the weights and matlab scripts? looking forward~ 

### ISSUE THREAD

**Issue by xuexiy1ge** [banterle/NoR-VDPNet#2]

**Comment by banterle** [comment]
We will be more than happy to send you the weights by email. We will publicly release them in the future.

There are no MATLAB scripts; the original code is in Python. All the source code is already publicly available on this git.

**Comment by xuexiy1ge** [comment]
I sent you an email yesterday. I don't know if it's blocked. My email address is tanglf111@qq.com. I would be very grateful if you could share the weights.

**Comment by xuexiy1ge** [comment]
> We will be more than happy to send you the weights by email. We will publicly release them in the future.
> 
> There are no MATLAB scripts; the original code is in Python. All the source code is already publicly available on this git.

I sent you an email yesterday. I don't know if it's blocked. My email address is tanglf111@qq.com. I would be very grateful if you could share the weights.

**Comment by banterle** [comment]
I have checked both email and the spam folder. Could you resend it to francesco.banterle@isti.cnr.it, please?

**Comment by xuexiy1ge** [comment]
> I have checked both email and the spam folder. Could you resend it to [francesco.banterle@isti.cnr.it](mailto:francesco.banterle@isti.cnr.it), please?

I sent you an email again. I don't know if you have received it. Would you like to you send me a copy of the weights to my email tanglf111@qq.com ?

**Comment by banterle** [comment]
Got it, thank you. I will answer you asap.
