### ISSUE TITLE
Will you be posting weights? I've been looking forward to it for a while

### ISSUE THREAD

**Issue by TIM-ysh** [banterle/NoR-VDPNet#3]

**Comment by banterle** [comment]
At the moments are available on request.
NOTE:
1) Weights for 8-bit images cover different distortions;
2) Weights for HDR, as written in the paper, cover only compression artifacts when using JPEG-XT.

Please send an email for the weights; if the two cases highlighted fit what you are interested in.

**Comment by TIM-ysh** [comment]
I have sent an email to francesco.banterle@isti.cnr.it but have not received a reply. Did I enter the wrong email address? Thank you.

**Comment by banterle** [comment]
Thank you for your interest. I did not receive the email, please send me it again. 
Please note, replies cannot be sent immediately at 3AM with time zone GMT+1.

**Comment by TIM-ysh** [comment]
OK, I posted it again just now. Please.

**Comment by banterle** [comment]
I understand that you posted again a message here. However, to send you the weights; you have to send me an email.

**Comment by TIM-ysh** [comment]
I sent the email but it may not have been received on your end due to an unknown error. My email is ysh_tim@163.com. Thank you very much.

**Comment by banterle** [comment]
OK, I will send you a Wetransfer. Please note that the current weights for SDR/8-bit images model blur, noise, and quantization, and the HDR weights models only JPEG-XT compression artifacts.

**Comment by banterle** [comment]
You should have received an email for downloading them.

**Comment by TIM-ysh** [comment]
Yes, I have received it. Thank you.
